
# This is an example of the kind of things you can do in a configuration file.
# All flags used by the client can be configured here. Run Certbot with
# "--help" to learn more about the available options.

# Use a 4096 bit RSA key instead of 2048
rsa-key-size = 4096

# Uncomment and update to register with the specified e-mail address
# email = admin@example.com

# Uncomment and update with domains to be included in the certificate
# domains = example.com, www.example.com

# Use a text interface instead of ncurses
text = True

# Authenticate by placing a file under .well-known/acme-challenge/ in specified webroot
authenticator = webroot
webroot-path = /var/www/html/letsencrypt
